In [2]:
import numpy as np
import pandas as pd
import matplotlib as mp

In [4]:
from google.colab import files
uploaded = files.upload()

Saving AWCustomers.csv to AWCustomers.csv

In [5]:
df= pd.read_csv("AWCustomers.csv")
df.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            18361 non-null  int64
 1   Title                 101 non-null    object
 2   FirstName             18361 non-null  object
 3   MiddleName            10572 non-null  object
 4   LastName              18361 non-null  object
 5   Suffix                3 non-null      object
 6   AddressLine1          18361 non-null  object
 7   AddressLine2          311 non-null    object
 8   City                  18361 non-null  object
 9   StateProvinceName     18361 non-null  object
 10  CountryRegionName     18361 non-null  object
 11  PostalCode            18361 non-null  object
 12  PhoneNumber           18361 non-null  object
 13  BirthDate             18361 non-null  object
 14  Education             18361 non-null  object
 15  Occupation            18361 non-null  object
 16  Gender                18361 non-null  object
 17  MaritalStatus         18361 non-null  object
 18  HomeOwnerFlag         18361 non-null  int64
 19  NumberCarsOwned       18361 non-null  int64
 20  NumberChildrenAtHome  18361 non-null  int64
 21  TotalChildren         18361 non-null  int64
 22  YearlyIncome          18361 non-null  int64
 23  LastUpdated           18361 non-null  object
dtypes: int64(6), object(18)
memory usage: 3.4+ MB

In [7]:
df.shape

(18361, 24)

In [8]:
df.columns

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [9]:
df.dtypes

CustomerID               int64
Title                   object
FirstName               object
MiddleName              object
LastName                object
Suffix                  object
AddressLine1            object
AddressLine2            object
City                    object
StateProvinceName       object
CountryRegionName       object
PostalCode              object
PhoneNumber             object
BirthDate               object
Education               object
Occupation              object
Gender                  object
MaritalStatus           object
HomeOwnerFlag            int64
NumberCarsOwned          int64
NumberChildrenAtHome     int64
TotalChildren            int64
YearlyIncome             int64
LastUpdated             object
dtype: object

In [10]:
df.isnull().sum()

CustomerID                  0
Title                   18260
FirstName                   0
MiddleName               7789
LastName                    0
Suffix                  18358
AddressLine1                0
AddressLine2            18050
City                        0
StateProvinceName           0
CountryRegionName           0
PostalCode                  0
PhoneNumber                 0
BirthDate                   0
Education                   0
Occupation                  0
Gender                      0
MaritalStatus               0
HomeOwnerFlag               0
NumberCarsOwned             0
NumberChildrenAtHome        0
TotalChildren               0
YearlyIncome                0
LastUpdated                 0
dtype: int64

In [12]:
selected_cols=["MaritalStatus",
               "Gender",
               "YearlyIncome",
               "TotalChildren",
               "Education",
               "Occupation",
               "HomeOwnerFlag",
               "NumberCarsOwned",
               "CountryRegionName"]
df_selected =df[selected_cols]

In [14]:
#numerical columns
num_cols = df_selected.select_dtypes(include=['int64','float64']).columns
df_selected[num_cols] = df_selected[num_cols].fillna(df_selected[num_cols].median())
#categorical columns
cat_cols = df_selected.select_dtypes(include=['object']).columns
df_selected[cat_cols] = df_selected[cat_cols].fillna(df_selected[cat_cols].mode().iloc[0])

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_selected[['YearlyIncome']] = scaler.fit_transform(
    df_selected[['YearlyIncome']]
)

In [18]:
df_selected['Income Bin'] = pd.qcut(
    df_selected['YearlyIncome'],
    q=4,
    labels=['Low','Medium','High','Very High']
)

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_selected[['YearlyIncome']] = scaler.fit_transform(
    df_selected[['YearlyIncome',]]
)

In [21]:
df_final = pd.get_dummies(
    df_selected,
    columns=[
        'Gender',
        'MaritalStatus',
        'HomeOwnerFlag'
    ],
    drop_first=True
)

In [22]:
print(df.head)

<bound method NDFrame.head of       MaritalStatus Gender  YearlyIncome  TotalChildren        Education  \
0                 M      M         81916              1        Bachelors
1                 M      M         81076              2  Partial College
2                 S      F         86387              0        Bachelors
3                 M      M         61481              2  Partial College
4                 S      M         51804              0  Partial College
...             ...    ...           ...            ...              ...
18356             M      F         52953              2  Graduate Degree
18357             S      F         60992              0        Bachelors
18358             S      F         51859              0  Partial College
18359             S      F         87177              0      High School
18360             M      F        136856              0  Graduate Degree

           Occupation  HomeOwnerFlag  NumberCarsOwned CountryRegionName
0            Clerical              1                3         Australia
1            Clerical              1                2            Canada
2            Clerical              0                3     United States
3      Skilled Manual              1                2    United Kingdom
4      Skilled Manual              1                1           Germany
...               ...            ...              ...               ...
18356  Skilled Manual              0                1     United States
18357  Skilled Manual              0                2         Australia
18358  Skilled Manual              0                2     United States
18359        Clerical              0                0            Canada
18360    Professional              1                2     United States

[18361 rows x 9 columns]>